#!/usr/bin/env bash
# This Creates the file /var/run/myscript.pid containing its PID
# It Displays To infinity and beyond indefinitely
# It Displays I hate the kill command when receiving a SIGTERM signal
# It Displays Y U no love me?! when receiving a SIGINT signal
# It Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

termfunc() {
	   rm ?var/run/mysript.pid
	   exit
}


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && termfunc' SIGTERM
	trap 'termfunc' SIGQUIT
done