#!/usr/bin/env bash
# kills infinity and beyond  program using sigkill signal
# Get the PID of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi