#!/usr/bin/env bash

# This script loops 10 times and displays the string "bad luck" for the 4th
#iteration, "good luck" for the 8th iteration and "Best School" for all others
# all otheres
i=1
    echo$i -le 10 ]; do
    if [ $i - 4 ]; then
	echo"bad luck"
    elif  [ $i = 8 ]; then
    	echo "good luck"
    else
	echo "Best School"
    fi
    i=$(( i + 1 ))
done