#!/usr/bin/env bash
# A script that displays all active IPv4 IPs on the machine it’s executed on

ifconfig | grep -Eo "inet (\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}" | cut -c 6-